### ISSUE TITLE
Allow pipeline relationships

### ISSUE THREAD

**Issue by jamclaug** [mrpaulandrew/ADF.procfwk#12]
Currently, if a worker pipeline fails it blocks all other pipeline executions, failing the entire execution.  A feature has been put on the backlog to allow this failure to be ignored and allow all other pipelines to execute.  In my experience, what is needed is a bit more complex.

For a single data platform you will have several to many data products that are generated.  These products each require certain pipelines to run, in order.  Often, data products can depend on common pipelines, but this is not always the case.  

For example, consider the following scenario:

```
id | pipeline name        | stage
----------------------------------
1  | data_source1_http    | 1
2  | trans_source1_stage  | 2
3  | trans_product1_load  | 3
4  | data_source2_odata   | 1
5  | trans_source2_stage  | 2
6  | trans_product2_load  | 3
7  | trans_product3_dwh   | 4
```
_trans_product3_dwh_ pulls data from the staging area for source1 and source 2.  _trans_product1_load_ only uses data from source1.  _trans_product2_load_ only uses data from source 2.

If pipeline _data_source1_http_ fails for some reason, then the execution for pipelines 2, 3 and 7 should be held up, but not 4, 5 and 6.  Those pipelines are independent of the failed pipeline and the subsequent products can be created without a problem.

This type of pipeline dependency/heirarchy would be very helpful as part of the orchestration framework.

**Comment by mrpaulandrew** [comment]
Thanks James, yes agreed. I've had similar conversations with Gapy in the comments of the v1.6 blog post.

https://mrpaulandrew.com/2020/05/19/adf-procfwk-v1-6-error-details-for-failed-activities-captured/

I'll look into implementing this using the 'Logical Predecessor' ID value already in the pipelines table.

**Comment by mrpaulandrew** [comment]
Hi James, I've done some more thinking on this one...

I'm going to add a new Property called 'FailureHandling'. This property could have 3 possible values....

1. **None** = The failure status is updated in the Current Execution table and the framework carries on regardless.

2. **Simple** = The failure status is updated in the Current Execution table. Downstream execution **stages** are marked as blocked and processing is stopped after the stage where the failure occurred.  This is basically what currently happens.

3. **Informed** = The failure status is updated in the Current Execution table. Downstream **pipelines** are marked as blocked (using the LogicalPredecessorId attribute in the Pipelines table). However, processing is allowed to continue. When the next execution stage starts only pipelines NOT blocked will be prepared and ran. 

Obviously for the third 'Informed' handling this logic requires the additional metadata in the LogicalPredecessorId attribute to be populated. Maybe the attribute needs a rename?

The key difference is:
-  Simple, blocks downstream stages and stops.
- Informed, blocks affected downstream pipelines and continues.

In any case, I'm fairly confident this could be implemented as a database only change without needing to alter the Data Factory activities.

What do you think?

Cheers

Paul

**Comment by jamclaug** [comment]
I really like your approach, as I use the Logical Predecessor column in my metadata.  The only issue I see with that is the situation where two sources, each handled by an independent pipeline, are predecessors to a single pipeline that uses data from both sources.  

This is my current situation, actually, and the way I would handle it is with a pipeline relationship table.  It can get ridiculously complicated, but in my experience that is how things often work.  Using a set of stored procedures to manage it - AddPipelineRelationship( parentPipelineId, childPipelineId) and DeletePipelineRelationship(pipelineRelationshipId) or something similar should cover it, or the user could just manipulate the junction table manually.

Make sense?

**Comment by mrpaulandrew** [comment]
Thanks @jamclaug yes, makes sense. Great point.
I think I'll remove the logical attribute and create this as a complete PipelineDependencies table so the 1:many situation you've described can be supported.

I'll work on this for the next major release.

Internal backlog item created.

Cheers
