### ISSUE TITLE
Use azure.datafactory.tools PS module for ADF deployment

### ISSUE THREAD

**Issue by NowinskiK** [mrpaulandrew/ADF.procfwk#14]
Then you can deploy the whole ADF code nicely with one line of code.

**Comment by NowinskiK** [comment]
Take a look at this PR #15

**Comment by mrpaulandrew** [comment]
Hey @NowinskiK do you just want to contribute to the repo and provide this enhancement?

Replacing the current script... https://github.com/mrpaulandrew/ADF.procfwk/blob/master/DeploymentTools/DataFactory/DeployProcFwkComponents.ps1

I expect complete release notes that can go into a blog as well as replacement YouTube video on using the new method.

We can make a big deal of the open source collaboration :-)

Cheers

**Comment by NowinskiK** [comment]
Sure... both approaches work for me. Let's talk about that later today or tomorrow.
