### ISSUE TITLE
Create a PowerShell script to get and set basic pipeline metadata for a given Data Factory resource.

### ISSUE THREAD

**Issue by mrpaulandrew** [mrpaulandrew/ADF.procfwk#22]
Scrap a list of pipelines from an ADF instance via Powershell and use it to populate the metadata database with a basic set of information using the stored procedure [procfwkHelpers].[AddPipelineViaPowerShell].

Sudo code...
Get-AzDataFactoryV2Pipeline
EXEC [procfwkHelpers].[AddPipelineViaPowerShell].

**Comment by mrpaulandrew** [comment]
Related twitter thread:
https://twitter.com/big_data_dan/status/1261467505362534401?s=20

Related SDK page:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.waitactivity.waittimeinseconds?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_WaitActivity_WaitTimeInSeconds

**Comment by NowinskiK** [comment]
@mrpaulandrew is this what you expected?

**Comment by mrpaulandrew** [comment]
Yes, perfect. Thanks. I'll do the release notes and raise the PR.
