### ISSUE TITLE
Previously cancelled worker pipeline executions fails when the framework is restarted

### ISSUE THREAD

**Issue by NJLangley** [mrpaulandrew/ADF.procfwk#37]
**Describe the bug**
If you cancel a running worker pipeline, the framework stops in the same way as if an error happened (in simple failure handling mode) . If you then restart the framework processing, instead of re-running the worker pipeline, it fails to reset the state and the parent framework pipeline fails without triggering any child pipelines.

**Affected services**
Which resource within the processing framework does this affect?
* All of them

**To Reproduce**
1. Trigger a new run in Data Factory
2. Cancel one of the worker pipelines
3. Wait for the current framework execution to complete
4. Check the current executions table - the cancelled pipeline should have a status of `Cancelled/Unknown`
5. Re-run the framework parent pipeline. The framework fails to restart the processing cleanly like it does for a failed execution.

**Expected behaviour**
A cancelled pipeline should be restart-able like a failed pipeline.

**Additional context**
I have a branch on my fork with a fix, will submit a PR with the details

**Comment by mrpaulandrew** [comment]
Replicated. Investigating fix.
