### ISSUE TITLE
Email alerts sent to blank email addresses when using specific alert bit flags

### ISSUE THREAD

**Issue by NJLangley** [mrpaulandrew/ADF.procfwk#38]
**Describe the bug**
When alerting is setup using the bit mask to specify specific alerts only, eg Errors, the proc to determine if alerts should be processed returned before the outcome was known. This meant a successful worker configured to only alert on failure would make the framework child pipeline fail when processing the alerts as it would attempt to send the alert without having a valid address to send it to.

**Affected services**
Which resource within the processing framework does this affect?
* All of them

**To Reproduce**
1. Modify `procfwk.PipelineAlertLink` to setup a worker pipeline to alert an email address only when an error occurs (`OutcomesBitValue = 4`). Ensure no other alerts are configured for the pipeline
2. Run the framework to process the pipeline successfully
3. In the ADF monitor view, the framework child pipeline will have a status of error from trying to send an email to a blank address

**Expected behaviour**
The framework should be checking the outcome of the worker pipeline to determine if there are any alerts to be sent based a bit-wise AND with `procfwk.PipelineAlertLink.OutcomesBitValue`.

**Additional context**
I have a branch on my fork with a fix, will submit a PR with the details

**Comment by mrpaulandrew** [comment]
Replicated. Investigating fix.
